### ISSUE TITLE
notifyItemChanged

### ISSUE THREAD

**Issue by df13954** [titanchen2000/GloriousRecyclerView#1]
notifyItemChanged无效，适配器不会刷新，滚动后才刷新。。

**Comment by titanchen2000** [comment]
Please change your question to english for the convenience of other people reading, thanks

when your data set changed, you should call
```java
 mRecyclerView.getAdapter().notifyDataSetChanged();
```
in your Activity/Fragment where your GloriousRecyclerView is.

see demo here[Line 67 in GloriousActivity.java](https://github.com/titanchen2000/GloriousRecyclerView/blob/master/app/src/main/java/com/xpc/gloriousrecyclerviewdemo/GloriousActivity.java)

**Comment by df13954** [comment]
I just want to refresh 1 tiem

**Comment by titanchen2000** [comment]
Since the real Adapter binded to GloriousRecyclerView is it's inner Adapter named GloriousAdapter , so, all the refresh operation should handled by GloriousAdapter .

You can refresh your data set like this:
```java
mRecyclerView.getAdapter().notifyDataSetChanged();
//should pay attention to if the headerView is present, if so , you positon should add one
mRecyclerView.getAdapter().notifyItemChanged(position);
mRecyclerView.getAdapter().notifyItemInserted(position);
mRecyclerView.getAdapter().notifyItemRemoved(position);
```

**Comment by df13954** [comment]
ok
